# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TamBoon' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    pod 'Kingfisher', '~> 4.10.0’
    pod 'IQKeyboardManagerSwift', '~> 6.0.4’
  # Pods for TamBoon

  target 'TamBoonTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
